- fail: 
    msg: "nginx_catchall_enable needs nginx_delete_default_site to be set!"
  when: not nginx_delete_default_site

- name: Create catchall config
  template:
    src: catchall.conf
    dest: /etc/nginx/sites-enabled/catchall.conf
  notify: nginx restart
