- name: Create global htpasswd file
  htpasswd:
    path: /etc/nginx/global_htpasswd
    name: "{{ nginx_global_auth_username }}"
    password: "{{ nginx_global_auth_password }}"

- name: Add nginx auth global config
  copy:
    content: |
      auth_basic "{{ nginx_global_auth_realm }}";
      auth_basic_user_file /etc/nginx/global_htpasswd;
    dest: /etc/nginx/conf.d/htpasswd.conf
  notify: nginx restart
