- import_tasks: packages.yml

- import_tasks: htpasswd.yml
  when: nginx_global_auth_realm != ''

- import_tasks: conf.yml

- import_tasks: snippets.yml
  when: nginx_generate_snippets

- include_tasks: proxy_pass.yml
  with_items: "{{ nginx_simple_proxy_passes }}"

- import_tasks: catchall.yml
  when: nginx_catchall_enable
