- include: packages.yml

- include: htpasswd.yml
  when: nginx_global_auth_realm != ''

- include: conf.yml

- include: snippets.yml
  when: nginx_generate_snippets

- include: proxy_pass.yml
  with_items: "{{ nginx_simple_proxy_passes }}"

- include: uwsgi_pass.yml
  with_items: "{{ nginx_simple_uwsgi_passes }}"

- include: catchall.yml
  when: nginx_catchall_enable
