- name: Ensure packages needed for nginx are present
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
    - ssl-cert # needed for snakeoil certs
    - python3-passlib # needed for some nginx-related ansible actions, such as htpasswd
